### ISSUE TITLE
Support for JSON data-descriptor

### ISSUE THREAD

**Issue by seank** [malcom2073/emslogview#2]
It would be nice if EMS-LV could read in the data descriptor, so that when the firmware code changes, things just "show up", with the proper scale etc. EMSTune has spoiled us in that respect.

Thanks,
Sean

**Comment by malcom2073** [comment]
It does as of 75ca219f24f7d9639d5139a63719802ec0721488, does that not work?

**Comment by seank** [comment]
Let me try! Thx.

**Comment by seank** [comment]
No, it did not work in aa65a6. I went to add a field to the view and EthanolPercentage was not there. Same with primary and secondary duty-cycle.

Looks like it's trying though:
DATALOG IMPLEMENTATION READ AND CHANGED
234094 records loaded

Thanks!

**Comment by malcom2073** [comment]
Ah so this is a new parameter. I am not handling new ones, just rearranged ones. I'll add that in.

**Comment by malcom2073** [comment]
Can you upload a log file which contains EthanolPercentage and the two duty-cycle variables?

**Comment by seank** [comment]
File shared via gDocs, link sent, thanks.
