### ISSUE TITLE
Add CSV export.

### ISSUE THREAD

**Issue by seank** [malcom2073/emslogview#3]
Can you add an option to export log data to a CSV file. EMSLogView is great, but for some advance analytics spreadsheets work better.

Related to this:
https://github.com/malcom2073/emstune/issues/27

Thanks,
Sean

**Comment by malcom2073** [comment]
Sean:

Stick a good log up that uses the new datalog descriptors for me?

**Comment by seank** [comment]
That should do it, thx!
[logs.zip](https://github.com/malcom2073/emslogview/files/276591/logs.zip)
